name: centos_dev

on:
  push:
    paths:
      - '.github/workflows/centos_dev.yml'

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: centos:7
    steps:
      - name: System basic setup
        run: |
          yum update -y && yum install -y curl openssl-devel git

      - name: RH csl setup
        run: |
          yum install -y centos-release-scl
          yum install -y devtoolset-11*
          scl enable devtoolset-11 'gcc --version'

      - name: Compile and install git
        run: |
          yum groupinstall 'Development Tools' -y
          yum install -y dh-autoreconf curl-devel expat-devel gettext-devel \
            openssl-devel perl-devel zlib-devel make autoconf gcc gcc-c++
          git clone --depth 1 https://github.com/git/git.git
          cd git
          scl enable devtoolset-11 'gcc --version && make configure && ./configure --prefix=/usr/local && make all && make install'
          git --version

      - name: Setup brew
        run: |
          wget -c https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
          scl enable devtoolset-11 'bash install.sh'
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew --version

      - name: Use brew
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install gcc-10

