name: release_lib

on:
  push:
    paths:
      - '.github/workflows/release_lib.yml'
      - 'scripts/prepare_centos_libs.sh'

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  run:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: run
        shell: bash
        run: |
          bash scripts/prepare_centos_libs.sh
          ls 
          ls prod_images/centos_to_ubuntu_libs

      - name: package
        shell: bash
        run: |
          cd prod_images
          tar cvzf ../centos_to_ubuntu_libs.tar.gz ./centos_to_ubuntu_libs

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Development Build"
          files: |
            centos_to_ubuntu_libs.tar.gz

      


